name: "Testing the Cache behaviour"
on: 

  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Download the repo

      - name: Caching the modules
        id: modules
        uses: actions/cache@v3
        with: 
          path: venv
          key: pip1-cache-${{ hashFiles('requirements.txt')}}

      - name: Installing PIP
        if: steps.modules.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        
      - name: Print modules
        run: |
          source venv/bin/activate
          pip freeze

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Download the repo

      - name: Caching the modules
        id: modules
        uses: actions/cache@v3
        with: 
          path: venv
          key: pip1-cache-${{ hashFiles('requirements.txt')}}

      - name: Installing PIP
        if: steps.modules.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

