name: "Testing the Cache behaviour"
on: 
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Download the repo

      - name: Caching the modules
        uses: actions/cache@v3
        with: 
          path: venv
          key: pip-cache-${{ hashFiles('requirements.txt')}}

      - name: Installing PIP
        run: |
          python -m virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Download the repo
      - name: Caching the modules
        uses: actions/cache@v3
        with: 
          path: venv1
          key: pip1-cache-${{ hashFiles('requirements.txt')}}
      - name: Installing PIP
        run: |
          python -m venv venv1
          source venv1/bin/activate
          pip install -r requirements.txt

