name: "Env Variables"
on: push

env:
    FLASK_SECRETS: ${{ secrets.FLASK_SECRETS }}

jobs:
    job1:
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: step 1
              run: echo "${{ env.FLASK_SECRETS }}"
            - name: step 2
              run: echo "${{ vars.API_URL }}"

    job2:
        runs-on: ubuntu-latest
        # needs: job1
        environment: preprod
        env:
            API_LINK: "${{ vars.API_URL }}"
        steps:
            - name: step 1
              run: echo "${{ env.FLASK_SECRETS }}"
            - name: step 2
              run: echo $API_LINK
