name: "Env Variables"
on: push

env:
    FLASK_SECRETS: hello-secret

jobs:
    job1:
        runs-on: ubuntu-latest
        env: 
            API_URL: dchero.app
        steps:
            - name: step 1
              run: echo "${{ env.FLASK_SECRETS }}"
            - name: step 2
              run: echo "${{ env.API_URL }}"

    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: step 1
              run: echo "${{ env.FLASK_SECRETS }}"
            - name: step 2
              run: echo "${{ env.API_URL }}"
