name: "Env Variables"
on: push

env:
    FLASK_SECRETS: ${{ secrets.FLASK_SECRETS }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: "${{ github.ref_name }}"
        env:
            API_LINK: "${{ vars.API_URL }}"
        steps:
            - name: step 1
              run: echo "${{ env.FLASK_SECRETS }}"
            - name: step 2
              run: echo $API_LINK
