name: "Testing the Py Version"
on: push

jobs:
  job1:
    strategy:
      matrix:
        pyversion: [3.7, 3,8, 3.9, 3.10]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Download the repo
      - uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.pyversion }}' 
      - run: |
            import sys
            print(sys.platform)
            print(sys.version_info)
        shell: python
